networks:
  proxy:
    external: true

services:
  angular-20-jwt-auth:
    image: uportal/angular-20-jwt-auth:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.todo-angular.rule=Host(`angular-20-jwt-auth.united-portal.com`)'
      - 'traefik.http.routers.todo-angular.tls=true'
      - 'traefik.http.routers.todo-angular.tls.certresolver=lets-encrypt'
      - 'traefik.http.routers.todo-angular.entrypoints=websecure'
      - 'traefik.http.services.todo-angular.loadbalancer.server.port=80'
    restart: unless-stopped
    ports:
      - 4000:80
    networks:
      - proxy

    environment:
      API_BASE_PATH: https://angular-20-jwt-auth.united-portal.com
